# client.toml - ExposeME Client Configuration

[client]
# Server WebSocket URL
#server_url = "wss://exposeme.arch7tect.org/tunnel-ws"
#server_url = "wss://localhost/tunnel-ws"
server_url = "wss://sip.flametree.dev.enfint.tech/tunnel-ws"
#insecure = true

# Authentication token (must match server config)
auth_token = "enfint-04d9d0bde4b2a06f3977379e"

# Tunnel identifier (choose unique name)
tunnel_id = "oo"

# Local service to forward requests to
local_target = "http://host.docker.internal:3000"
#local_target = "http://localhost:3000"

# Auto-reconnect on connection loss
auto_reconnect = true

# Delay between reconnection attempts (seconds)
reconnect_delay_secs = 5
