# client.toml - ExposeME Client Configuration

[client]
# Server WebSocket URL
server_url = "wss://exposeme.arch7tect.org:8081"

# Authentication token (must match server config)
auth_token = "dev"

# Tunnel identifier (choose unique name)
tunnel_id = "my-tunnel"

# Local service to forward requests to
local_target = "http://host.docker.internal:3000"

# Auto-reconnect on connection loss
auto_reconnect = true

# Delay between reconnection attempts (seconds)
reconnect_delay_secs = 5
