# client.toml - ExposeME Client Configuration

[client]
# Server WebSocket URL
server_url = "wss://exposeme.arch7tect.org:8081"

# Authentication token (must match server config)
auth_token = "arch7tect-ca840484c238fa6d7c983029"

# Tunnel identifier (choose unique name)
tunnel_id = "arch7tect-tunnel"

# Local service to forward requests to
local_target = "http://localhost:8000"

# Auto-reconnect on connection loss
auto_reconnect = true

# Delay between reconnection attempts (seconds)
reconnect_delay_secs = 5