# docker-compose.yml - Improved version with better SSL handling

services:
  exposeme-server:
    image: arch7tect/exposeme-server:latest
    container_name: exposeme-server
#    restart: unless-stopped

    ports:
      - "80:80"       # HTTP (ACME challenges + redirects)
      - "443:443"     # HTTPS

    volumes:
      # Server configuration
      - ./config/server.toml:/etc/exposeme/server.toml:ro
      # SSL certificates storage
      - ./certs:/etc/exposeme/certs:rw

    environment:
      # Domain configuration
      - EXPOSEME_DOMAIN=${EXPOSEME_DOMAIN:-exposeme.arch7tect.org}
      - EXPOSEME_EMAIL=${EXPOSEME_EMAIL:-arch7tect@gmail.com}

      # SSL configuration
      - EXPOSEME_STAGING=false
      - EXPOSEME_WILDCARD=true
      - EXPOSEME_ROUTING_MODE=both

      # DNS Provider (DigitalOcean)
      - EXPOSEME_DNS_PROVIDER=${EXPOSEME_DNS_PROVIDER:-digitalocean}
      - EXPOSEME_DIGITALOCEAN_TOKEN=${EXPOSEME_DIGITALOCEAN_TOKEN:-}
      - EXPOSEME_CLOUDFLARE_TOKEN=${EXPOSEME_CLOUDFLARE_TOKEN:-}

      # Auth token
      - EXPOSEME_AUTH_TOKEN=${EXPOSEME_AUTH_TOKEN:-dev}

      # Logging
      - RUST_LOG=${RUST_LOG:-info}
      - RUST_BACKTRACE=1

      # Other
      - EXPOSEME_REQUEST_TIMEOUT=${EXPOSEME_REQUEST_TIMEOUT:-120}

    # Security settings
    security_opt:
      - no-new-privileges:true

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.2'

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

    # Add environment file support
    env_file:
      - .env
