# server.toml - ExposeME Server Configuration

[server]
# HTTP server settings (for redirects and ACME challenges)
http_bind = "0.0.0.0"
http_port = 80

# HTTPS server settings
https_port = 443

# WebSocket server settings
ws_bind = "0.0.0.0"
ws_port = 8081

# Domain name (required for HTTPS)
domain = "exposeme2.arch7tect.org"

[ssl]
# Enable HTTPS with automatic certificates
enabled = true

# Certificate provider: "letsencrypt" or "manual"
provider = "selfsigned"

# Email for Let's Encrypt registration
email = "arch7tect@gmail.com"

# Use staging environment (for testing)
staging = true

# Directory to cache certificates
cert_cache_dir = "./exposeme-certs"

[auth]
# Authentication tokens
tokens = [
    "dev",
    "team-token-1",
    "team-token-2"
]

[limits]
# Maximum concurrent tunnels
max_tunnels = 50

# Request timeout in seconds
request_timeout_secs = 30