# client.toml - ExposeME Client Configuration
# docker run -it --rm -v ./client.toml:/etc/exposeme/client.toml arch7tect/exposeme-client:latest

[client]
# Server WebSocket URL
server_url = "wss://sip.flametree.dev.enfint.tech:8081"

# Authentication token (must match server config)
auth_token = "your-secure-token-here"

# Tunnel identifier (choose unique name)
tunnel_id = "my-dev-tunnel"

# Local service to forward requests to
local_target = "http://host.docker.internal:8000"

# Auto-reconnect on connection loss
auto_reconnect = true

# Delay between reconnection attempts (seconds)
reconnect_delay_secs = 5