# config/server.toml - Server configuration for Docker

[server]
# Bind to all interfaces in container
http_bind = "0.0.0.0"
http_port = 80
https_port = 443
ws_bind = "0.0.0.0"
ws_port = 8081

# Domain will be overridden via environment variable
domain = "localhost"

[ssl]
enabled = false
provider = "letsencrypt"
# Email will be overridden via environment variable
email = "admin@localhost"
# Staging will be overridden via environment variable
staging = true
cert_cache_dir = "/etc/exposeme/certs"

[auth]
# Tokens for client authorization
# In production better to use environment variables
tokens = [
    "dev-token",
    "telegram-bot-production",
    "github-webhook-production",
    "stripe-webhook-production"
]

[limits]
max_tunnels = 100
request_timeout_secs = 30