# config/server.toml - Server configuration for Docker

[server]
# Bind to all interfaces in container
http_bind = "0.0.0.0"
http_port = 80
https_port = 443
ws_bind = "0.0.0.0"
ws_port = 8081

# Domain will be overridden via environment variable
domain = "exposeme.arch7tect.org"
routing_mode = "path"

[ssl]
enabled = true
provider = "letsencrypt"

# Email will be overridden via environment variable
email = "arch7tect@gmail.com"

# Staging will be overridden via environment variable
staging = false
cert_cache_dir = "/etc/exposeme/certs"
wildcard=true
dns_provider = { provider = "digitalocean", config = { api_token = "your-do-token" } }

[auth]
# Tokens for client authorization
# In production better to use environment variables
tokens = [
    "dev",
    "team-token-1",
    "team-token-2"
]

[limits]
max_tunnels = 100
request_timeout_secs = 30