# config/server.toml - Server configuration for Docker

[server]
# Bind to all interfaces in container
http_bind = "0.0.0.0"
http_port = 80
https_port = 443
ws_bind = "0.0.0.0"
ws_port = 8081

# Domain will be overridden via environment variable
domain = "proxy2.arch7tect.org"

[ssl]
enabled = true
provider = "letsencrypt"
# Email will be overridden via environment variable
email = "arch7tect@gmail.com"
# Staging will be overridden via environment variable
staging = true
cert_cache_dir = "/etc/exposeme/certs"

[auth]
# Tokens for client authorization
# In production better to use environment variables
tokens = [
    "arch7tect-ca840484c238fa6d7c983029",
    "enfint-04d9d0bde4b2a06f3977379e"
]

[limits]
max_tunnels = 100
request_timeout_secs = 30