[build]
public_url = "/"
target = "index.html"
dist = "dist"
release = true

[wasm-opt]
enabled = true
level = "z"

[serve]
# The IP addresses to serve on (new plural format)
addresses = ["127.0.0.1"]
# The port to serve on
port = 8080
# Auto-reload when files change
watch = []

[clean]
# Whether to clean output dir before building
dist_dir = true
cargo = false